name: Auto-update Go SDK

on:
  schedule:
    - cron: '0 2 * * *' # Запуск каждый день в 02:00 UTC
  workflow_dispatch:      # Возможность запустить вручную

jobs:
  update-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Нужно для пуша коммитов и тегов

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Нужно для проверки существующих тегов

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Install Tools
        run: |
          sudo apt-get install -y jq
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

      - name: Generate SDK
        run: make generate

      - name: Check for Changes
        id: git_status
        run: |
          if [ -n "$(git status --porcelain clo_cloud.gen.go go.mod go.sum)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in SDK or Modules."
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes in generated code."
          fi

      - name: Commit and Push Changes
        if: steps.git_status.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add clo_cloud.gen.go go.mod go.sum
          
          git commit -m "chore: update sdk and go.mod to version $(jq -r '.info.version' openapi.final.json)"
          git push

      - name: Create and Push Tag
        if: steps.git_status.outputs.changed == 'true'
        run: make release # Таргет из Makefile создаст тег vX.Y.Z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`
