name: Auto-update Go SDK

on:
  # push:
  #   branches: [ "main" ]
  #   paths-ignore:
  #     - 'README.md'
  #     - '.gitignore'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install oapi-codegen
        run: |
            go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
            # Убеждаемся, что GOPATH/bin находится в PATH
            echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate SDK
        run: make all

      - name: Check for Changes
        id: git_status
        run: |
          if [ -n "$(git status --porcelain clo_cloud.gen.go go.mod go.sum client.go)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected by CI generation."
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No generation changes detected."
          fi

      - name: Commit and Push Changes
        if: steps.git_status.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add clo_cloud.gen.go go.mod go.sum client.go
          git commit -m "chore: auto-update sdk generation [skip ci]"
          git push

      - name: Release Patch Version
        if: success() && github.ref == 'refs/heads/main'
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            make release
